"""empty message

Revision ID: 909bf5a66994
Revises: 
Create Date: 2023-11-10 21:17:17.244502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909bf5a66994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mp3_file', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('mp3_file')
        batch_op.drop_column('language')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
